application: partistietokanta
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: www/app/index.html
  upload: www/app/index.html
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  auth_fail_action: unauthorized
- url: /css
  static_dir: www/app/css
  auth_fail_action: unauthorized
- url: /js
  static_dir: www/app/js
  auth_fail_action: unauthorized
- url: /lib
  static_dir: www/app/lib
  auth_fail_action: unauthorized
- url: /partials
  static_dir: www/app/partials
  auth_fail_action: unauthorized
- url: /etusivu
  static_dir: www/app/etusivu
  auth_fail_action: unauthorized
- url: /koira
  static_dir: www/app/koira
  auth_fail_action: unauthorized
- url: /img
  static_dir: www/app/img
  auth_fail_action: unauthorized
- url: /ckeditor
  static_dir: www/app/ckeditor
  auth_fail_action: unauthorized
- url: /CompactHistory
  script: main.app
  login: admin
  auth_fail_action: unauthorized
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
